on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install fixed pyDataverse version from GitHub (includes schema patch)
      - name: Install compatible pyDataverse
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/IQSS/pyDataverse.git

      # Upload repository to Harvard Dataverse
      - name: Send repo to Dataverse
        uses: IQSS/dataverse-uploader@v1.6
        with:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
          DATAVERSE_SERVER: https://dataverse.harvard.edu   
          DATAVERSE_DATASET_DOI: doi:10.7910/DVN/63YPGN
          DELETE: True
          PUBLISH: False

