on:
  workflow_dispatch: # Allow manual triggering from the Actions tab

jobs:
  upload_to_dataverse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Dataverse
        uses: IQSS/dataverse-uploader@v1 # Use the Dataverse Uploader Action
        with:
          DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }} # Your Dataverse Personal Access Token
          DATAVERSE_URL: "https://dataverse.harvard.edu" # URL of the Harvard Dataverse instance
          DOI: "doi:10.7910/DVN/63YPGN" # Replace with your dataset's DOI
